In [1]:
import numpy as np

arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [2]:
#Python program for
# Creation of Arrays
import numpy as np

# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [3]:
import numpy as np

# creating array
arr = np.array([2, 4, 6, 8, 10])

# creating copy of array
c = arr.copy()

# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))

# changing original array
# this will not effect copy
arr[0] = 12

# printing array and copy
print("original array- ", arr)
print("copy- ", c)


id of arr 132183872514032
id of c 132183655835728
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [4]:
# Let's define our function
# Parameters: Input Array
def sum(array):

	# Set variable for our final answer
	sum = 0

	# Parse through our array
	for i in array:

		# Continuously add current element
		# to final sum
		sum += i

	# Return our sum
	return sum


# Create a test array
testArray = [1, 3, 34, 92, 29, 48, 20.3]

# Test our function
print('The sum of your numbers is ' + str(sum(testArray)))


The sum of your numbers is 227.3


In [5]:
import numpy as np
# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [6]:
#The result includes the start index, but excludes the end index
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [7]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
#The copy SHOULD NOT be affected by the changes made to the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

In [ ]:
#The view SHOULD be affected by the changes made to the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

In [8]:
# Check if Array Owns its Data
# copies owns the data, and views does not own the data, but how can we check this?
#Every NumPy array has the attribute base that returns None if the array owns the data.
#Otherwise, the base  attribute refers to the original object.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [10]:
# Create an array with 5 dimensions using ndmin
#using a vector with values 1,2,3,4 and verify that last dimension has value 4:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [11]:
#Convert the following 1-D array with 12 elements into a 2-D array.

#The outermost dimension will have 4 arrays, each with 3 elements:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

# importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [13]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [14]:
#The version string is stored under __version__ attribute.
import pandas as pd

print(pd.__version__)



2.0.3


In [15]:
#A Pandas Series is like a column in a table.

#It is a one-dimensional array holding data of any type.
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)
#If nothing else is specified, the values are labeled with their index number.
#First value has index 0, second value has index 1 etc.
#This label can be used to access a specified value.
#Return the first value of the Series:

print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [16]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


In [17]:
#A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)


#Pandas use the loc attribute to return one or more specified row(s)
#refer to the row index:
print(df.loc[0])
#Returns a pandas series


#use a list of indexes:
print(df.loc[[0, 1]])
#When using [], the result is a Pandas DataFrame.

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [19]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df.to_string())
#use to_string() to print the entire DataFrame.

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [21]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df)
#If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows


   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [22]:
import pandas as pd

print(pd.options.display.max_rows)
#The number of rows returned is defined in Pandas option settings.

#You can check your system's maximum rows with the pd.options.display.max_rows statement.

60


In [23]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('Data.csv')

print(df)

print(pd.options.display.max_rows)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
9999


In [24]:
#Load a Python Dictionary into a DataFrame   JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [25]:
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")
# how : {‘left’, ‘right’, ‘outer’, ‘inner’}, default ‘inner’


'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35

'The second DataFrame'

fruit  wholesaler_price
0   banana                65
1    apple                68
2  avocado                75

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21                68
1   banana            14                65
2  avocado            35                75

In [26]:
#Merging two data frames with different number of elements
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
# here both common DataFrame elements are in df1 and df2,
# so it extracts apple, banana, grapes from df1 and df2.
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

'The second DataFrame'

fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21              65.0
1   banana            14              68.0
2  avocado            35               NaN
3    grape            38              71.0

In [28]:
# Pandas dataframe.groupby() function is used to split the data into groups based on some criteria.
# Pandas objects can be split on any of their axes.
# The abstract definition of grouping is to provide a mapping of labels to group names.
# importing pandas as pd
import pandas as pd

# Creating the dataframe
df = pd.read_csv("nba.csv")

# Print the dataframe
print(df.head())    #Returns  top n (5 by default) rows of a data frame or series.



            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0  


In [29]:
# applying groupby() function to
# group the data on team value.
gk = df.groupby('Team')

# Let's print the first entries
# in all the groups formed.
gk.first()

Name  Number Position   Age Height  \
Team                                                                          
Atlanta Hawks                   Kent Bazemore    24.0       SF  26.0    6-5   
Boston Celtics                  Avery Bradley     0.0       PG  25.0    6-2   
Brooklyn Nets                Bojan Bogdanovic    44.0       SG  27.0    6-8   
Charlotte Hornets               Nicolas Batum     5.0       SG  27.0    6-8   
Chicago Bulls                Cameron Bairstow    41.0       PF  25.0    6-9   
Cleveland Cavaliers       Matthew Dellavedova     8.0       PG  25.0    6-4   
Dallas Mavericks              Justin Anderson     1.0       SG  22.0    6-6   
Denver Nuggets                 Darrell Arthur     0.0       PF  28.0    6-9   
Detroit Pistons                  Joel Anthony    50.0        C  33.0    6-9   
Golden State Warriors         Leandro Barbosa    19.0       SG  33.0    6-3   
Houston Rockets                  Trevor Ariza     1.0       SF  30.0    6-8   
Indiana Pacers                    Lavoy Allen     5.0       PF  27.0    6-9   
Los Angeles Clippers             Cole Aldrich    45.0        C  27.0   6-11   
Los Angeles Lakers               Brandon Bass     2.0       PF  31.0    6-8   
Memphis Grizzlies                Jordan Adams     3.0       SG  21.0    6-5   
Miami Heat                         Chris Bosh     1.0       PF  32.0   6-11   
Milwaukee Bucks         Giannis Antetokounmpo    34.0       SF  21.0   6-11   
Minnesota Timberwolves        Nemanja Bjelica    88.0       PF  28.0   6-10   
New Orleans Pelicans            Alexis Ajinca    42.0        C  28.0    7-2   
New York Knicks                 Arron Afflalo     4.0       SG  30.0    6-5   
Oklahoma City Thunder            Steven Adams    12.0        C  22.0    7-0   
Orlando Magic                  Dewayne Dedmon     3.0        C  26.0    7-0   
Philadelphia 76ers                Elton Brand    42.0       PF  37.0    6-9   
Phoenix Suns                     Eric Bledsoe     2.0       PG  26.0    6-1   
Portland Trail Blazers        Cliff Alexander    34.0       PF  20.0    6-8   
Sacramento Kings                   Quincy Acy    13.0       SF  25.0    6-7   
San Antonio Spurs           LaMarcus Aldridge    12.0       PF  30.0   6-11   
Toronto Raptors               Bismack Biyombo     8.0        C  23.0    6-9   
Utah Jazz                       Trevor Booker    33.0       PF  28.0    6-8   
Washington Wizards              Alan Anderson     6.0       SG  33.0    6-6   

                        Weight                College      Salary  
Team                                                               
Atlanta Hawks            201.0           Old Dominion   2000000.0  
Boston Celtics           180.0                  Texas   7730337.0  
Brooklyn Nets            216.0         Oklahoma State   3425510.0  
Charlotte Hornets        200.0  Virginia Commonwealth  13125306.0  
Chicago Bulls            250.0             New Mexico    845059.0  
Cleveland Cavaliers      198.0           Saint Mary's   1147276.0  
Dallas Mavericks         228.0               Virginia   1449000.0  
Denver Nuggets           235.0                 Kansas   2814000.0  
Detroit Pistons          245.0                   UNLV   2500000.0  
Golden State Warriors    194.0         North Carolina   2500000.0  
Houston Rockets          215.0                   UCLA   8193030.0  
Indiana Pacers           255.0                 Temple   4050000.0  
Los Angeles Clippers     250.0                 Kansas   1100602.0  
Los Angeles Lakers       250.0                    LSU   3000000.0  
Memphis Grizzlies        209.0                   UCLA   1404600.0  
Miami Heat               235.0           Georgia Tech  22192730.0  
Milwaukee Bucks          222.0                Arizona   1953960.0  
Minnesota Timberwolves   240.0             Louisville   3950001.0  
New Orleans Pelicans     248.0             California   4389607.0  
New York Knicks          210.0                   UCLA   8000000.0  
Oklahoma City Th

In [30]:
# Finding the values contained in the "Boston Celtics" group
gk.get_group('Boston Celtics')

Name            Team  Number Position   Age Height  Weight  \
0     Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1       Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2      John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3       R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4     Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
5      Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0   
6     Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7      Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
8      Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0   
9      Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0   
10  Jared Sullinger  Boston Celtics     7.0        C  24.0    6-9   260.0   
11    Isaiah Thomas  Boston Celtics     4.0       PG  27.0    5-9   185.0   
12      Evan Turner  Boston Celtics    11.0       SG  27.0    6-7   220.0   
13      James Young  Boston Celtics    13.0       SG  20.0    6-6   215.0   
14     Tyler Zeller  Boston Celtics    44.0        C  26.0    7-0   253.0   

              College      Salary  
0               Texas   7730337.0  
1           Marquette   6796117.0  
2   Boston University         NaN  
3       Georgia State   1148640.0  
4                 NaN   5000000.0  
5                 NaN  12000000.0  
6                 LSU   1170960.0  
7             Gonzaga   2165160.0  
8          Louisville   1824360.0  
9      Oklahoma State   3431040.0  
10         Ohio State   2569260.0  
11         Washington   6912869.0  
12         Ohio State   3425510.0  
13           Kentucky   1749840.0  
14     North Carolina   2616975.0

In [31]:
#Indentation
j = 1

while(j<= 5):
	print(j)
	j = j + 1


1
2
3
4
5
